[book]
title = "FRP for FRPools"
authors = ["spwashi's learning studies curriculum"]
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
additional-css = ["custom.css"]

[output.html.playground]
editable = true
line-numbers = true
